# Generated by Django 3.2.7 on 2021-09-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='physical_add',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='Purposeofloan',
            field=models.TextField(),
        ),
    ]
